export { default as BuyHome } from './BuyHome'
export { default as SellHome } from './SellHome'
export { default as RentHome } from './RentHome'
export { default as WealthPlanning } from './WealthPlanning'
export { default as Email } from './Email'
export { default as Location } from './Location'
export { default as WhatsApp } from './Whatsapp'
