// Code generated by Slice Machine. DO NOT EDIT.

import ArticlesViewSection from './ArticlesViewSection';
import BlogPostCard from './BlogPostCard';
import CtaBlock from './CtaBlock';

export {
	ArticlesViewSection,
	BlogPostCard,
	CtaBlock,
};

export const components = {
	articles_view_section: ArticlesViewSection,
	blog_post_card: BlogPostCard,
	cta_block: CtaBlock,
};
