export const POSTAL_DISTRICTS = [
	{ title: 'D01 Raffles Place', value: 'D01_Raffles_Place' },
	{ title: 'D01 Cecil', value: 'D01_Cecil' },
	{ title: 'D01 Marina', value: 'D01_Marina' },
	{ title: "D01 People's Park", value: 'D01_Peoples_Park' },
	{ title: 'D02 Anson', value: 'D02_Anson' },
	{ title: 'D02 Tanjong Pagar', value: 'D02_Tanjong_Pagar' },
	{ title: 'D03 Queenstown', value: 'D03_Queenstown' },
	{ title: 'D03 Tiong Bahru', value: 'D03_Tiong_Bahru' },
	{ title: 'D04 Telok Blangah', value: 'D04_Telok_Blangah' },
	{ title: 'D04 Harbourfront', value: 'D04_Harbourfront' },
	{ title: 'D05 Pasir Panjang', value: 'D05_Pasir_Panjang' },
	{ title: 'D05 Hong Leong Garden', value: 'D05_Hong_Leong_Garden' },
	{
		title: 'D05 Clementi New Town',
		value: 'D05_Clementi_New_Town',
	},
	{ title: 'D06 High Street', value: 'D06_High_Street' },
	{ title: 'D06 Beach Road (part)', value: 'D06_Beach_Road_part' },
	{ title: 'D07 Middle Road', value: 'D07_Middle_Road' },
	{ title: 'D07 Golden Mile', value: 'D07_Golden_Mile' },
	{ title: 'D08 Little India', value: 'D08_Little_India' },
	{ title: 'D09 Orchard', value: 'D09_Orchard' },
	{ title: 'D09 Cairnhill', value: 'D09_Cairnhill' },
	{ title: 'D09 River Valley', value: 'D09_River_Valley' },
	{ title: 'D10 Ardmore', value: 'D10_Ardmore' },
	{ title: 'D10 Bukit Timah', value: 'D10_Bukit_Timah' },
	{ title: 'D10 Holland Road', value: 'D10_Holland_Road' },
	{ title: 'D10 Tanglin', value: 'D10_Tanglin' },
	{ title: 'D11 Watten Estate', value: 'D11_Watten_Estate' },
	{ title: 'D11 Novena', value: 'D11_Novena' },
	{ title: 'D11 Thomson', value: 'D11_Thomson' },
	{ title: 'D12 Balestier', value: 'D12_Balestier' },
	{ title: 'D12 Toa Payoh', value: 'D12_Toa_Payoh' },
	{ title: 'D12 Serangoon', value: 'D12_Serangoon' },
	{ title: 'D13 Macpherson', value: 'D13_Macpherson' },
	{ title: 'D13 Braddell', value: 'D13_Braddell' },
	{ title: 'D14 Geylang', value: 'D14_Geylang' },
	{ title: 'D14 Eunos', value: 'D14_Eunos' },
	{ title: 'D15 Katong', value: 'D15_Katong' },
	{ title: 'D15 Joo Chiat', value: 'D15_Joo_Chiat' },
	{ title: 'D15 Amber Road', value: 'D15_Amber_Road' },
	{ title: 'D16 Bedok', value: 'D16_Bedok' },
	{ title: 'D16 Upper East Coast', value: 'D16_Upper_East_Coast' },
	{ title: 'D16 Eastwood', value: 'D16_Eastwood' },
	{ title: 'D16 Kew Drive', value: 'D16_Kew_Drive' },
	{ title: 'D17 Loyang', value: 'D17_Loyang' },
	{ title: 'D17 Changi', value: 'D17_Changi' },
	{ title: 'D18 Tampines', value: 'D18_Tampines' },
	{ title: 'D18 Pasir Ris', value: 'D18_Pasir_Ris' },
	{ title: 'D19 Serangoon Garden', value: 'D19_Serangoon_Garden' },
	{ title: 'D19 Hougang', value: 'D19_Hougang' },
	{ title: 'D19 Punggol', value: 'D19_Punggol' },
	{ title: 'D20 Bishan', value: 'D20_Bishan' },
	{ title: 'D20 Ang Mo Kio', value: 'D20_Ang_Mo_Kio' },
	{ title: 'D21 Upper Bukit Timah', value: 'D21_Upper_Bukit_Timah' },
	{ title: 'D21 Clementi Park', value: 'D21_Clementi_Park' },
	{ title: 'D21 Ulu Pandan', value: 'D21_Ulu_Pandan' },
	{ title: 'D22 Jurong', value: 'D22_Jurong' },
	{ title: 'D23 Hillview', value: 'D23_Hillview' },
	{ title: 'D23 Dairy Farm', value: 'D23_Dairy_Farm' },
	{ title: 'D23 Bukit Panjang', value: 'D23_Bukit_Panjang' },
	{ title: 'D23 Choa Chu Kang', value: 'D23_Choa_Chu_Kang' },
	{ title: 'D24 Lim Chu Kang', value: 'D24_Lim_Chu_Kang' },
	{ title: 'D24 Tengah', value: 'D24_Tengah' },
	{ title: 'D25 Kranji', value: 'D25_Kranji' },
	{ title: 'D25 Woodgrove', value: 'D25_Woodgrove' },
	{ title: 'D26 Upper Thomson', value: 'D26_Upper_Thomson' },
	{ title: 'D26 Springleaf', value: 'D26_Springleaf' },
	{ title: 'D27 Yishun', value: 'D27_Yishun' },
	{ title: 'D27 Sembawang', value: 'D27_Sembawang' },
	{ title: 'D28 Seletar', value: 'D28_Seletar' },
]

export const PROPERTY_TYPE = [
	{ title: 'Landed', value: 'landed' },
	{ title: 'Condo', value: 'condo' },
	{ title: 'HDB', value: 'hdb' },
	{ title: 'Commerical', value: 'commerical' },
]

export const TENURE_TYPE = [
	{ title: 'Freehold', value: 'freehold' },
	{ title: '99 Years', value: '99_years' },
]

export const MRT_STATIONS = [
	{ title: 'Admiralty (NS10)', value: 'Admiralty_NS10' },
	{ title: 'Aljunied (EW9)', value: 'Aljunied_EW9' },
	{ title: 'Ang Mo Kio (NS16)', value: 'Ang_Mo_Kio_NS16' },
	{ title: 'Bartley (CC12)', value: 'Bartley_CC12' },
	{ title: 'Bayfront (DT16 CE1)', value: 'Bayfront_DT16_CE1' },
	{ title: 'Bedok (EW5)', value: 'Bedok_EW5' },
	{ title: 'Bedok North (DT29)', value: 'Bedok_North_DT29' },
	{ title: 'Bedok Reservoir (DT30)', value: 'Bedok_Reservoir_DT30' },
	{ title: 'Beauty World (DT5)', value: 'Beauty_World_DT5' },
	{ title: 'Bendemeer (DT23)', value: 'Bendemeer_DT23' },
	{ title: 'Bencoolen (DT21)', value: 'Bencoolen_DT21' },
	{ title: 'Bishan (NS17 CC15)', value: 'Bishan_NS17_CC15' },
	{ title: 'Boon Keng (NE9)', value: 'Boon_Keng_NE9' },
	{ title: 'Boon Lay (EW27)', value: 'Boon_Lay_EW27' },
	{ title: 'Botanic Gardens (CC19 DT9)', value: 'Botanic_Gardens_CC19_DT9' },
	{ title: 'Bras Basah (CC2)', value: 'Bras_Basah_CC2' },
	{ title: 'Braddell (NS18)', value: 'Braddell_NS18' },
	{ title: 'Bugis (EW12 DT14)', value: 'Bugis_EW12_DT14' },
	{ title: 'Buangkok (NE15)', value: 'Buangkok_NE15' },
	{ title: 'Buona Vista (EW21 CC22)', value: 'Buona_Vista_EW21_CC22' },
	{ title: 'Bukit Batok (NS2)', value: 'Bukit_Batok_NS2' },
	{ title: 'Bukit Gombak (NS3)', value: 'Bukit_Gombak_NS3' },
	{ title: 'Bukit Panjang (DT1 BP6)', value: 'Bukit_Panjang_DT1_BP6' },
	{ title: 'Caldecott (CC17 TE9)', value: 'Caldecott_CC17_TE9' },
	{ title: 'Canberra (NS12)', value: 'Canberra_NS12' },
	{ title: 'Cashew (DT2)', value: 'Cashew_DT2' },
	{ title: 'Changi Airport (CG2)', value: 'Changi_Airport_CG2' },
	{ title: 'Choa Chu Kang (NS4 BP1)', value: 'Choa_Chu_Kang_NS4_BP1' },
	{ title: 'Chinese Garden (EW25)', value: 'Chinese_Garden_EW25' },
	{ title: 'Chinatown (NE4 DT19)', value: 'Chinatown_NE4_DT19' },
	{ title: 'City Hall (NS25 EW13)', value: 'City_Hall_NS25_EW13' },
	{ title: 'Clarke Quay (NE5)', value: 'Clarke_Quay_NE5' },
	{ title: 'Clementi (EW23)', value: 'Clementi_EW23' },
	{ title: 'Commonwealth (EW20)', value: 'Commonwealth_EW20' },
	{ title: 'Dakota (CC8)', value: 'Dakota_CC8' },
	{ title: 'Dhoby Ghaut (NS24 NE6 CC1)', value: 'Dhoby_Ghaut_NS24_NE6_CC1' },
	{ title: 'Downtown (DT17)', value: 'Downtown_DT17' },
	{ title: 'Dover (EW22)', value: 'Dover_EW22' },
	{ title: 'Eunos (EW7)', value: 'Eunos_EW7' },
	{ title: 'Esplanade (CC3)', value: 'Esplanade_CC3' },
	{ title: 'Expo (DT35 CG1)', value: 'Expo_DT35_CG1' },
	{ title: 'Farrer Park (NE8)', value: 'Farrer_Park_NE8' },
	{ title: 'Farrer Road (CC20)', value: 'Farrer_Road_CC20' },
	{ title: 'Fort Canning (DT20)', value: 'Fort_Canning_DT20' },
	{ title: 'Geylang Bahru (DT24)', value: 'Geylang_Bahru_DT24' },
	{ title: 'Gul Circle (EW30)', value: 'Gul_Circle_EW30' },
	{ title: 'HarbourFront (NE1 CC29)', value: 'HarbourFront_NE1_CC29' },
	{ title: 'Haw Par Villa (CC25)', value: 'Haw_Par_Villa_CC25' },
	{ title: 'Hillview (DT3)', value: 'Hillview_DT3' },
	{ title: 'Holland Village (CC21)', value: 'Holland_Village_CC21' },
	{ title: 'Hougang (NE14)', value: 'Hougang_NE14' },
	{ title: 'Jalan Besar (DT22)', value: 'Jalan_Besar_DT22' },
	{ title: 'Joo Koon (EW29)', value: 'Joo_Koon_EW29' },
	{ title: 'Jurong East (NS1 EW24)', value: 'Jurong_East_NS1_EW24' },
	{ title: 'Kaki Bukit (DT28)', value: 'Kaki_Bukit_DT28' },
	{ title: 'Kallang (EW10)', value: 'Kallang_EW10' },
	{ title: 'Kembangan (EW6)', value: 'Kembangan_EW6' },
	{ title: 'Kent Ridge (CC24)', value: 'Kent_Ridge_CC24' },
	{ title: 'King Albert Park (DT6)', value: 'King_Albert_Park_DT6' },
	{ title: 'Kovan (NE13)', value: 'Kovan_NE13' },
	{ title: 'Kranji (NS7)', value: 'Kranji_NS7' },
	{ title: 'Labrador Park (CC27)', value: 'Labrador_Park_CC27' },
	{ title: 'Lakeside (EW26)', value: 'Lakeside_EW26' },
	{ title: 'Lavender (EW11)', value: 'Lavender_EW11' },
	{ title: 'Little India (NE7 DT12)', value: 'Little_India_NE7_DT12' },
	{ title: 'Lorong Chuan (CC14)', value: 'Lorong_Chuan_CC14' },
	{ title: 'MacPherson (CC10 DT26)', value: 'MacPherson_CC10_DT26' },
	{ title: 'Marina Bay (NS27 CE2 TE20)', value: 'Marina_Bay_NS27_CE2_TE20' },
	{ title: 'Marina South Pier (NS28)', value: 'Marina_South_Pier_NS28' },
	{ title: 'Marsiling (NS)', value: 'Marsiling_NS' },
	{ title: 'Mattar (DT25)', value: 'Mattar_DT25' },
	{ title: 'Mountbatten (CC7)', value: 'Mountbatten_CC7' },
	{ title: 'Newton (NS21 DT11)', value: 'Newton_NS21_DT11' },
	{ title: 'Nicoll Highway (CC5)', value: 'Nicoll_Highway_CC5' },
	{ title: 'Novena (NS20)', value: 'Novena_NS20' },
	{ title: 'one-north (CC23)', value: 'one_north_CC23' },
	{ title: 'Orchard (NS22 TE14)', value: 'Orchard_NS22_TE14' },
	{ title: 'Outram Park (NE3 EW16 TE17)', value: 'Outram_Park_NE3_EW16_TE17' },
	{ title: 'Pasir Panjang (CC26)', value: 'Pasir_Panjang_CC26' },
	{ title: 'Pasir Ris (EW1)', value: 'Pasir_Ris_EW1' },
	{ title: 'Paya Lebar (EW8 CC9)', value: 'Paya_Lebar_EW8_CC9' },
	{ title: 'Pioneer (EW28)', value: 'Pioneer_EW28' },
	{ title: 'Potong Pasir (NE10)', value: 'Potong_Pasir_NE10' },
	{ title: 'Promenade (CC4 DT15)', value: 'Promenade_CC4_DT15' },
	{ title: 'Punggol (NE17 PTC)', value: 'Punggol_NE17_PTC' },
	{ title: 'Queenstown (EW19)', value: 'Queenstown_EW19' },
	{ title: 'Raffles Place (EW14 NS26)', value: 'Raffles_Place_EW14_NS26' },
	{ title: 'Redhill (EW18)', value: 'Redhill_EW18' },
	{ title: 'Rochor (DT13)', value: 'Rochor_DT13' },
	{ title: 'Sembawang (NS11)', value: 'Sembawang_NS11' },
	{ title: 'Sengkang (NE16 STC)', value: 'Sengkang_NE16_STC' },
	{ title: 'Serangoon (CC13 NE12)', value: 'Serangoon_CC13_NE12' },
	{ title: 'Simei (EW3)', value: 'Simei_EW3' },
	{ title: 'Sixth Avenue (DT7)', value: 'Sixth_Avenue_DT7' },
	{ title: 'Somerset (NS23)', value: 'Somerset_NS23' },
	{ title: 'Stadium (CC6)', value: 'Stadium_CC6' },
	{ title: 'Stevens (DT10 TE11)', value: 'Stevens_DT10_TE11' },
	{ title: 'Tai Seng (CC11)', value: 'Tai_Seng_CC11' },
	{ title: 'Tampines (EW2 DT32)', value: 'Tampines_EW2_DT32' },
	{ title: 'Tampines East (DT33)', value: 'Tampines_East_DT33' },
	{ title: 'Tampines West (DT31)', value: 'Tampines_West_DT31' },
	{ title: 'Tan Kah Kee (DT8)', value: 'Tan_Kah_Kee_DT8' },
	{ title: 'Tanah Merah (EW4 CG)', value: 'Tanah_Merah_EW4_CG' },
	{ title: 'Telok Ayer (DT18)', value: 'Telok_Ayer_DT18' },
	{ title: 'Telok Blangah (CC28)', value: 'Telok_Blangah_CC28' },
	{ title: 'Tiong Bahru (EW17)', value: 'Tiong_Bahru_EW17' },
	{ title: 'Toa Payoh (NS19)', value: 'Toa_Payoh_NS19' },
	{ title: 'Tuas Crescent (EW31)', value: 'Tuas_Crescent_EW31' },
	{ title: 'Tuas Link (EW33)', value: 'Tuas_Link_EW33' },
	{ title: 'Tuas West Road (EW32)', value: 'Tuas_West_Road_EW32' },
	{ title: 'Upper Changi (DT34)', value: 'Upper_Changi_DT34' },
	{ title: 'Ubi (DT27)', value: 'Ubi_DT27' },
	{ title: 'Woodlands (NS9 TE2)', value: 'Woodlands_NS9_TE2' },
	{ title: 'Woodlands North (TE1)', value: 'Woodlands_North_TE1' },
	{ title: 'Woodlands South (TE3)', value: 'Woodlands_South_TE3' },
	{ title: 'Woodleigh (NE11)', value: 'Woodleigh_NE11' },
	{ title: 'Yew Tee (NS5)', value: 'Yew_Tee_NS5' },
	{ title: 'Yio Chu Kang (NS15)', value: 'Yio_Chu_Kang_NS15' },
	{ title: 'Yishun (NS13)', value: 'Yishun_NS13' },

	{ title: 'Springleaf (TE4)', value: 'Springleaf_TE4' },
	{ title: 'Lentor (TE5)', value: 'Lentor_TE5' },
	{ title: 'Mayflower (TE6)', value: 'Mayflower_TE6' },
	{ title: 'Bright Hill (TE7)', value: 'Bright_Hill_TE7' },
	{ title: 'Upper Thomson (TE8)', value: 'Upper_Thomson_TE8' },
	{ title: 'Napier (TE12)', value: 'Napier_TE12' },
	{ title: 'Orchard Boulevard (TE13)', value: 'Orchard_Boulevard_TE13' },
	{ title: 'Great World (TE15)', value: 'Great_World_TE15' },
	{ title: 'Havelock (TE16)', value: 'Havelock_TE16' },
	{ title: 'Maxwell (TE18)', value: 'Maxwell_TE18' },
	{ title: 'Shenton Way (TE19)', value: 'Shenton_Way_TE19' },
	{ title: 'Gardens by the Bay (TE22)', value: 'Gardens_by_the_Bay_TE22' },
	{ title: 'Tanjong Rhu (TE23)', value: 'Tanjong_Rhu_TE23' },
	{ title: 'Katong Park (TE24)', value: 'Katong_Park_TE24' },
	{ title: 'Tanjong Katong (TE25)', value: 'Tanjong_Katong_TE25' },
	{ title: 'Marine Parade (TE26)', value: 'Marine_Parade_TE26' },
	{ title: 'Marine Terrace (TE27)', value: 'Marine_Terrace_TE27' },
	{ title: 'Siglap (TE28)', value: 'Siglap_TE28' },
	{ title: 'Bayshore (TE29)', value: 'Bayshore_TE29' },
]
